### ISSUE TITLE
SAC + SALE + DroQ jax Implementation

### ISSUE THREAD

**Issue by araffin** [sfujim/TD7#1]
Hello,
thanks for open-sourcing the code =) (I'm glad to see that state representation learning is still a thing, I also worked on it [some years ago](https://arxiv.org/abs/1901.08651)...)

I just wanted to share my SAC + SALE jax implementation: https://github.com/araffin/sbx/pull/13
For now, it only has the state representation implemented (not the 3 other tricks) and it works quite well, also when combined with [DroQ](https://twitter.com/araffin2/status/1575439865222660098).

The main advantage of this implementation is that it is much faster than the PyTorch equivalent (when using the appropriate trick, SAC with Jax runs at 2000+ FPS on MuJoCo, so [only 8 minutes](https://twitter.com/araffin2/status/1590714601754497024) for 1M steps =)).

**Comment by sfujim** [comment]
Thanks for sharing!
