### ISSUE TITLE
Bug when using no prioritzation

### ISSUE THREAD

**Issue by conglu1997** [sfujim/TD7#4]
Hi, I think the code is missing `self.prioritized=False` in the False case.

https://github.com/sfujim/TD7/blob/41bcaefe094c411b0c65257087d6534e2548c2c9/buffer.py#L32C9-L32C9

Additionally, these should be conditional:

https://github.com/sfujim/TD7/blob/41bcaefe094c411b0c65257087d6534e2548c2c9/TD7.py#L262

https://github.com/sfujim/TD7/blob/41bcaefe094c411b0c65257087d6534e2548c2c9/TD7.py#L290

**Comment by sfujim** [comment]
Good catch, thank you.
